url: https://tm.paperswelove.ro
baseurl: ''
enforce_ssl: tm.paperswelove.ro
safe: true
lsi: false
sass:
    style: compressed

compass:
  logo: "/images/logo.png"
  author: "Papers We Love Romania"
  tagline: "Community built around reading, discussing and learning more about academic computer science papers."
  include_content: true
  include_analytics: false

markdown: kramdown
highlighter: rouge

permalink: pretty

# Settings for deploy rake task
username:        papers-we-love-ro
repo:            tm.paperswelove.ro
branch:          source
relative_source: ../tm.paperswelove.ro/
destination:     ../tm.paperswelove.ro-pages/
production_url:  https://tm.paperswelove.ro
source_url:      https://github.com/papers-we-love-ro/tm.paperswelove.ro
